spring.application.name=research.assistant

# Gemini API Key (your actual key)
spring.ai.google.genai.api-key=${LLM_API_KEY}
# Model
# CHANGE THIS LINE
spring.ai.google.genai.chat.options.model=gemini-flash-latest




# Optional tuning
spring.ai.google.genai.chat.options.temperature=0.7

spring.ai.google.genai.chat.options.google-search-retrieval=false


# Server
server.port=8080

# Enable ChatClient
spring.ai.chat.client.enabled=true



spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.tool.hbm2ddl=DEBUG

#frontend
#frontend.url=${FRONTEND_URL}

